---
- name: Install NGINX
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-enabled/*

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: unlink /etc/nginx/sites-enabled/default
  ignore_errors: yes

- name: Disable NGINX Default Virtual Host
  become: yes
  file:
    path: "/etc/nginx/sites-enabled/*"
    state: absent

- name: Disable NGINX Default Virtual Host
  become: yes
  file:
    path: /etc/nginx/sites-available/webserver.conf
    state: absent

- name: Create NGINX Config File For WebServer
  become: yes
  file:
    path: /etc/nginx/sites-available/webserver.conf
    state: touch

- name: Amend NGINX Config File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/webserver.conf
      marker: ""
      block: |
        server {
            listen 80;
            location / {
                proxy_pass http://127.0.0.1:5000/; 
                proxy_set_header Authorization "";
                proxy_read_timeout 90s;
            }
        }

- name: Link NGINX webserver Reverse Proxy
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/webserver.conf /etc/nginx/sites-enabled/default

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
