---

- hosts: server
  gather_facts: yes
  any_errors_fatal: true
  roles:
    - nginx # Installation and configuration of nginx
    - postgres # Installation and configuration of postgres
    - python # Deploy and configuration of python web app
    - role: mrlesmithjr.netplan # Configuration of the network
      become: yes
      netplan_enabled: true
      netplan_config_file: /etc/netplan/my-awesome-netplan.yaml
      netplan_renderer: networkd
      netplan_configuration:
        network:
          version: 2
          ethernets:
            ens160:
              dhcp4: no
              addresses:
                - 10.0.0.2/18
              #nameservers:
              #  addresses: [8.8.8.8]
              #routes:
              #  - to: default
              #    via: 10.0.0.1/18

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600
