---  
- name: Install dependencies for PostgreSQL
  apt:
      name:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
      update_cache : true
      state : latest

- name: Install PostgreSQL 
  apt:
      name:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
      update_cache: true 
      state: present

- name: Ensure the PostgreSQL service is running
  service:
      name=postgresql
      state=started
      enabled=yes

- name: Create the database specified in group_vars
  become: true
  become_user: postgres
  postgresql_db:
      name={{ db_name }}
      template='template0'
      state=present

- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_user:
      db={{ db_name }}
      name={{ db_user }}
      password={{ db_password }}
      priv=ALL
      state=present

- name: Ensure user does not have unnecessary permissions
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }}
         role_attr_flags=NOSUPERUSER,NOCREATEDB
         state=present
  
         #- name: Add some dummy data to our database
         #become: true
         #become_user: postgres
         #shell: psql {{ db_name }} < /tmp/dump.sql
